#!/bin/bash
# ============================================================
# DNS++ Phase 1 Integration Test
# Tests Algorithm 1 (Proximity Routing) on a single broker
#
# Scenario:
#   Subscriber A: London (51.5, -0.1)
#   Subscriber B: Berlin (52.5, 13.4)
#   Publisher 1:  Paris  (48.8, 2.3)  → closer to London
#   Publisher 2:  Warsaw (52.2, 21.0) → closer to Berlin
#
# Expected:
#   Paris  → Both receive (first pub, closest=∞)
#   Warsaw → Only Berlin receives (closer to Berlin than Paris)
#
# Clients run with --plaintext on purpose: this script is a regression test
# for proximity routing, not for the homomorphic layer. Encrypted clients
# would additionally depend on /tmp/dnspp_heps_full.key having been written
# by this very broker, which makes the test racy for no added coverage.
# ============================================================

set -e

BROKER_PORT=8080
BROKER_BIN="./build/dns_broker"
CLIENT_BIN="./build/test_client"
BROKER_IP=127.0.0.1
SERVICE="test.integration"
LOG_DIR="/tmp/dnspp_test"
BROKER_CONF="$LOG_DIR/test_broker.conf"

rm -rf "$LOG_DIR"
mkdir -p "$LOG_DIR"

BROKER_PID=""
cleanup() {
    if [ -n "$BROKER_PID" ]; then
        kill "$BROKER_PID" 2>/dev/null || true
        wait "$BROKER_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

echo "=== DNS++ Phase 1 Integration Test ==="
echo ""

# --- Generate broker config (dns_broker takes a config file, not positional args) ---
cat > "$BROKER_CONF" <<EOF
# Generated by scripts/run_integration_test.sh — single root broker
broker_id=test
listen_port=$BROKER_PORT
parent_addr=
coords=0.0,0.0
brake_limit=2
brake_window=10
EOF
echo "[OK] Wrote broker config to $BROKER_CONF"

# Start broker
$BROKER_BIN "$BROKER_CONF" > "$LOG_DIR/broker.log" 2>&1 &
BROKER_PID=$!

# Wait until the broker is actually listening. A root broker generates a
# 2048-bit Paillier key before entering its event loop, which takes seconds.
READY=false
for _ in $(seq 1 60); do
    if ! kill -0 "$BROKER_PID" 2>/dev/null; then
        break
    fi
    if grep -q "Listening on port" "$LOG_DIR/broker.log" 2>/dev/null; then
        READY=true
        break
    fi
    sleep 0.5
done

if [ "$READY" != true ]; then
    echo "FAIL: Broker did not become ready within 30s"
    cat "$LOG_DIR/broker.log"
    exit 1
fi
echo "[OK] Broker listening on port $BROKER_PORT (PID $BROKER_PID)"

# Start subscribers (5s timeout each)
timeout 5 $CLIENT_BIN sub $BROKER_IP $BROKER_PORT $SERVICE 51.5 -0.1 --plaintext \
    > "$LOG_DIR/sub_london.log" 2>&1 &
SUB_LON_PID=$!
timeout 5 $CLIENT_BIN sub $BROKER_IP $BROKER_PORT $SERVICE 52.5 13.4 --plaintext \
    > "$LOG_DIR/sub_berlin.log" 2>&1 &
SUB_BER_PID=$!
sleep 0.5
echo "[OK] Subscribers started (London + Berlin)"

# Publish from Paris
$CLIENT_BIN pub $BROKER_IP $BROKER_PORT $SERVICE 48.8 2.3 Paris-edge-1 --plaintext
sleep 0.5
echo "[OK] Published from Paris"

# Publish from Warsaw
$CLIENT_BIN pub $BROKER_IP $BROKER_PORT $SERVICE 52.2 21.0 Warsaw-edge-1 --plaintext
sleep 0.5
echo "[OK] Published from Warsaw"

# Wait for subscribers to finish (timeout)
wait $SUB_LON_PID 2>/dev/null || true
wait $SUB_BER_PID 2>/dev/null || true

# Kill broker
cleanup
BROKER_PID=""

# --- Verify results ---
echo ""
echo "--- Results ---"

LONDON_GOT_PARIS=$(grep -c "Paris" "$LOG_DIR/sub_london.log" 2>/dev/null || true)
LONDON_GOT_PARIS=${LONDON_GOT_PARIS:-0}
LONDON_GOT_WARSAW=$(grep -c "Warsaw" "$LOG_DIR/sub_london.log" 2>/dev/null || true)
LONDON_GOT_WARSAW=${LONDON_GOT_WARSAW:-0}
BERLIN_GOT_PARIS=$(grep -c "Paris" "$LOG_DIR/sub_berlin.log" 2>/dev/null || true)
BERLIN_GOT_PARIS=${BERLIN_GOT_PARIS:-0}
BERLIN_GOT_WARSAW=$(grep -c "Warsaw" "$LOG_DIR/sub_berlin.log" 2>/dev/null || true)
BERLIN_GOT_WARSAW=${BERLIN_GOT_WARSAW:-0}

echo "London subscriber: Paris=$LONDON_GOT_PARIS, Warsaw=$LONDON_GOT_WARSAW"
echo "Berlin subscriber: Paris=$BERLIN_GOT_PARIS, Warsaw=$BERLIN_GOT_WARSAW"
echo ""

PASS=true

if [ "$LONDON_GOT_PARIS" -lt 1 ]; then
    echo "FAIL: London should have received Paris"
    PASS=false
fi
if [ "$LONDON_GOT_WARSAW" -ge 1 ]; then
    echo "FAIL: London should NOT have received Warsaw (farther than Paris)"
    PASS=false
fi
if [ "$BERLIN_GOT_PARIS" -lt 1 ]; then
    echo "FAIL: Berlin should have received Paris (first pub, closest=∞)"
    PASS=false
fi
if [ "$BERLIN_GOT_WARSAW" -lt 1 ]; then
    echo "FAIL: Berlin should have received Warsaw (closer than Paris)"
    PASS=false
fi

if [ "$PASS" = true ]; then
    echo "=== ALL TESTS PASSED ==="
    exit 0
else
    echo "=== TESTS FAILED ==="
    echo ""
    echo "--- Broker log ---"
    cat "$LOG_DIR/broker.log"
    echo ""
    echo "--- London subscriber log ---"
    cat "$LOG_DIR/sub_london.log"
    echo ""
    echo "--- Berlin subscriber log ---"
    cat "$LOG_DIR/sub_berlin.log"
    exit 1
fi
